### ISSUE TITLE
DunnyData or DummyData?

### ISSUE THREAD

**Issue by hlh2001** [xncaffe/caffe_convert_onnx#1]
Thank you for your contributions to the model conversion. I wonder if the supported caffe operator DunnyData means DummyData and how should we construct a tensor padded with zeros? Just like thes examples, what should be modified?
the first example
layer {
  name: "add_prev93_zeropad"
  type: "DummyData"
  top: "add_prev93_zeropad"
  dummy_data_param {
    num: 1
    channels: 32
    height: 17
    width: 17
  }
}

Traceback (most recent call last):
  File "convert_main.py", line 73, in <module>
  File "convert_main.py", line 69, in main
  File "convert_main.py", line 39, in single_convert
  File "src/caffe_model.py", line 238, in caffe_mapper_to_onnx
  File "src/mapper/layer_mapper.py", line 51, in mapping
KeyError: 'DummyData'
[158612] Failed to execute script 'convert_main' due to unhandled exception!

the second example
layer {
  name: "add_prev93_zeropad"
  type: "DunnyData"
  top: "add_prev93_zeropad"
  dunny_data_param {
    num: 1
    channels: 32
    height: 17
    width: 17
  }
}

Traceback (most recent call last):
  File "convert_main.py", line 73, in <module>
  File "convert_main.py", line 69, in main
  File "convert_main.py", line 37, in single_convert
  File "convert_main.py", line 23, in loadcaffemodel
  File "check_model.py", line 18, in check
  File "google/protobuf/text_format.py", line 725, in Merge
  File "google/protobuf/text_format.py", line 793, in MergeLines
  File "google/protobuf/text_format.py", line 818, in MergeLines
  File "google/protobuf/text_format.py", line 837, in _ParseOrMerge
  File "google/protobuf/text_format.py", line 967, in _MergeField
  File "google/protobuf/text_format.py", line 1042, in _MergeMessageField
  File "google/protobuf/text_format.py", line 934, in _MergeField
google.protobuf.text_format.ParseError: 335:3 : Message type "caffe.LayerParameter" has no field named "dunny_data_param".
[158695] Failed to execute script 'convert_main' due to unhandled exception!

the third example
layer {
  name: "add_prev93_zeropad"
  type: "DunnyData"
  top: "add_prev93_zeropad"
  dummy_data_param {
    num: 1
    channels: 32
    height: 17
    width: 17
  }
}

Traceback (most recent call last):
  File "convert_main.py", line 73, in <module>
  File "convert_main.py", line 69, in main
  File "convert_main.py", line 39, in single_convert
  File "src/caffe_model.py", line 238, in caffe_mapper_to_onnx
  File "src/mapper/layer_mapper.py", line 51, in mapping
KeyError: 'DunnyData'
[158780] Failed to execute script 'convert_main' due to unhandled exception!

**Comment by xncaffe** [comment]
This should be DummyData.

**Comment by xncaffe** [comment]
> Thank you for your contributions to the model conversion. I wonder if the supported caffe operator DunnyData means DummyData and how should we construct a tensor padded with zeros? Just like thes examples, what should be modified? the first example layer { name: "add_prev93_zeropad" type: "DummyData" top: "add_prev93_zeropad" dummy_data_param { num: 1 channels: 32 height: 17 width: 17 } }
> 
> Traceback (most recent call last): File "convert_main.py", line 73, in File "convert_main.py", line 69, in main File "convert_main.py", line 39, in single_convert File "src/caffe_model.py", line 238, in caffe_mapper_to_onnx File "src/mapper/layer_mapper.py", line 51, in mapping KeyError: 'DummyData' [158612] Failed to execute script 'convert_main' due to unhandled exception!
> 
> the second example layer { name: "add_prev93_zeropad" type: "DunnyData" top: "add_prev93_zeropad" dunny_data_param { num: 1 channels: 32 height: 17 width: 17 } }
> 
> Traceback (most recent call last): File "convert_main.py", line 73, in File "convert_main.py", line 69, in main File "convert_main.py", line 37, in single_convert File "convert_main.py", line 23, in loadcaffemodel File "check_model.py", line 18, in check File "google/protobuf/text_format.py", line 725, in Merge File "google/protobuf/text_format.py", line 793, in MergeLines File "google/protobuf/text_format.py", line 818, in MergeLines File "google/protobuf/text_format.py", line 837, in _ParseOrMerge File "google/protobuf/text_format.py", line 967, in _MergeField File "google/protobuf/text_format.py", line 1042, in _MergeMessageField File "google/protobuf/text_format.py", line 934, in _MergeField google.protobuf.text_format.ParseError: 335:3 : Message type "caffe.LayerParameter" has no field named "dunny_data_param". [158695] Failed to execute script 'convert_main' due to unhandled exception!
> 
> the third example layer { name: "add_prev93_zeropad" type: "DunnyData" top: "add_prev93_zeropad" dummy_data_param { num: 1 channels: 32 height: 17 width: 17 } }
> 
> Traceback (most recent call last): File "convert_main.py", line 73, in File "convert_main.py", line 69, in main File "convert_main.py", line 39, in single_convert File "src/caffe_model.py", line 238, in caffe_mapper_to_onnx File "src/mapper/layer_mapper.py", line 51, in mapping KeyError: 'DunnyData' [158780] Failed to execute script 'convert_main' due to unhandled exception!

Hi,The data type in your prototxt is configured as DummyData. We currently only parse the type Input. It is recommended that you modify the type as:
layer {
name: "add_prev93_zeropad"
type: "Input"
top: "add_prev93_zeropad"
input_param {
shape {
dim: 1
dim: 32
dim: 17
dim: 17
}
}
}

This modification has no impact on model conversion
